<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccountTypeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('account_types')->insert([
            [
                'name' => 'ECN',
                'slug' => 'ecn',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'ECN',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Standard',
                'slug' => 'standard',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'Standard',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STD5',
                'slug' => 'std5',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'STD5',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STD10',
                'slug' => 'std10',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'STD10',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STD15',
                'slug' => 'std15',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'STD15',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STD20',
                'slug' => 'std20',
                'category' => 'individual',
                'account_group_id' => null,
                'account_group' => 'STD20',
                'minimum_deposit' => null,
                'leverage' => 0,
                'currency' => null,
                'allow_create_account' => null,
                'type' => null,
                'commission_structure' => null,
                'trade_open_duration' => 10,
                'maximum_account_number' => 3,
                'account_group_balance' => 0,
                'account_group_equity' => 0,
                'descriptions' => null,
                'color' => 'FDB022',
                'status' => 'active',
                'edited_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
